name: face-age-gender-recognition
dependencies:
<<<<<<< HEAD
  - python
=======
>>>>>>> 8ba4e498d75668b8bd22e7309d07e30b69a85c36
  - tensorflow
  - opencv
  - matplotlib
  - pip
  - numpy
  - pandas
  - scikit-learn
  - keras
  - pip:
    - requests