name: face-recognition
dependencies:
  - python=3.9.0
  - tensorflow==2.6.0
  - opencv
  - matplotlib
  - pip
  - numpy
  - pandas
  - scikit-learn
  - keras
  - pip:
    - segmentation-models
    - albumentations
    - requests